(()=>{
 'use strict';const C=PrimingCore,E=MechanismEngine,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let worker=null,result=null,reference;
 const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=v=>v===null||!Number.isFinite(v)?'—':Math.abs(v)>=1e5||Math.abs(v)>0&&Math.abs(v)<.001?v.toExponential(2):Number(v.toPrecision(3)).toLocaleString('en',{maximumFractionDigits:5});
 const percent=x=>x===null?'Not defined':`${Math.round(x*100)}%`;
 const labels={p1:'Initial response P1',ppr:'Paired-pulse ratio','ss:5':'5 Hz steady state / P1','ss:20':'20 Hz steady state / P1','ss:100':'100 Hz steady state / P1','ss:200':'200 Hz steady state / P1','r:0.1':'Recovery at 100 ms','r:0.3':'Recovery at 300 ms','r:1':'Recovery at 1 s',restTS:'Resting TS fraction','cum:200':'200 Hz cumulative release','r:0.5':'Recovery at 500 ms','ss:10':'10 Hz steady state / P1','ss:50':'50 Hz steady state / P1'};
 const defaultIds=Object.keys(labels).slice(0,9),extraIds=Object.keys(labels).slice(9);
 const qualLabels={strongDown:'Strongly decreased',down:'Decreased',mildDown:'Mildly decreased',same:'Unchanged',mildUp:'Mildly increased',up:'Increased',strongUp:'Strongly increased'};
 function targetCard(id){return `<div class="target" data-id="${id}"><h3>${labels[id]}</h3><label class="qual-only"><span class="hint">Compared with WT</span><select data-field="level" aria-label="${labels[id]} direction"><option value="unknown">Unknown / not measured</option>${Object.entries(qualLabels).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label><div class="quant-only"><div class="two"><label>Mean<input data-field="mean" type="number" step="any" aria-label="${labels[id]} mean"></label><label>Units<select data-field="unit"><option value="absolute">${id==='p1'||id.startsWith('cum:')?'Vesicles':'Absolute readout'}</option><option value="ratio" ${id==='p1'?'selected':''}>Mutant / WT</option></select></label></div><details class="uncertainty"><summary>Uncertainty</summary><label>Type<select data-field="uncertainty"><option value="none">Not provided (10% scale)</option><option value="sem">SEM</option><option value="sd">SD</option><option value="ci">95% confidence interval</option></select></label><label>SD / SEM<input data-field="error" type="number" min="0" step="any"></label><div class="two"><label>CI lower<input data-field="low" type="number" step="any"></label><label>CI upper<input data-field="high" type="number" step="any"></label></div><p class="hint">SD and SEM are used as supplied, without sample-size conversion. A 95% CI uses a normal approximation.</p></details></div><label>Weight<select data-field="weight"><option value="0">Ignore</option><option value="0.5">Low</option><option value="1" selected>Normal</option><option value="3">High</option></select></label></div>`}
 $('#reference').innerHTML=Object.entries(C.PRESETS).filter(([key])=>key!=='sciadv-hk').map(([key,p])=>`<option value="${key}" ${key==='sciadv'?'selected':''}>${esc(p.label)}</option>`).join('')+'<option value="custom">Custom parameter set</option>';
 $('#targetInputs').innerHTML=defaultIds.map(targetCard).join('');$('#extraInputs').innerHTML=extraIds.map(targetCard).join('');
 $('#qualRanges').innerHTML=Object.entries(E.QUAL).map(([key,[low,high]])=>`<label>${qualLabels[key]}</label><div class="two" data-range="${key}"><input aria-label="${qualLabels[key]} lower ratio" value="${low}" min="0" type="number" step="any"><input aria-label="${qualLabels[key]} upper ratio" value="${Number.isFinite(high)?high:''}" min="0" type="number" step="any"></div>`).join('');
 function readReference(){if($('#reference').value==='custom'){const parsed=JSON.parse($('#customReference').value);const p=parsed.params||parsed.reference||parsed;for(const key of Object.keys(C.resolvePreset('sciadv'))){if(!(key in p)&&typeof C.resolvePreset('sciadv')[key]==='number')throw Error('Custom reference is missing '+key)}return {...p}}return C.resolvePreset($('#reference').value,'publication')}
 function refreshReference(){try{reference=readReference();$('#wtN').textContent=`WT: ${fmt(reference.nSites)}`;$('#wtP').textContent=`WT: ${fmt(reference.pRel0)}`;$('#mutantN').value=reference.nSites;$('#mutantP').value=reference.pRel0;$('#parameterBounds').innerHTML=Object.entries(E.NAMES).map(([key,label])=>{const b=E.defaultBounds(reference,key);return `<div class="bound" data-key="${key}"><label><input type="checkbox" data-allow ${E.DEFAULT_KEYS.includes(key)?'checked':''}> ${label}</label><div class="two"><label>Minimum<input data-min type="number" value="${b[0]}" step="any"></label><label>Maximum<input data-max type="number" value="${b[1]}" step="any"></label></div></div>`}).join('');$('#progress').textContent='Reference ready. Describe the mutant phenotype.'}catch(e){$('#progress').textContent=e.message}}
 $('#reference').addEventListener('change',()=>{$('#customReferenceBox').hidden=$('#reference').value!=='custom';if($('#reference').value!=='custom')refreshReference()});
 $('#customReference').addEventListener('change',refreshReference);
 ['N','P'].forEach(k=>$('#lock'+k).addEventListener('change',()=>$('#mutant'+k).disabled=!$('#lock'+k).checked));
 function mode(){const m=$('#inputMode').value;$('#inferenceForm').className=m;$('#modeHint').textContent=m==='qualitative'?'Directions become broad ranges. Unknown observations carry zero weight.':'Enter means and optionally uncertainty. Blank measurements carry zero weight.'}
 $('#inputMode').addEventListener('change',mode);mode();
 function cost(){const text={fast:'Small screening search, suitable for exploration. Alternatives and identifiability will be limited.',standard:'Broader, staged searches; more computation. Larger subsets run only if simpler candidates miss the phenotype.',exhaustive:'Highest computational cost. Every subset up to the selected maximum is optimized from multiple starts; numerical search is still finite.'};$('#costHint').textContent=text[$('#searchMode').value]}
 $('#searchMode').addEventListener('change',cost);cost();refreshReference();
 const numbers=s=>s.split(/[\s,;]+/).filter(Boolean).map(Number);
 function buildRequest(){
  reference=readReference();const locks={};if($('#lockN').checked)locks.nSites=+$('#mutantN').value;if($('#lockP').checked)locks.pRel0=+$('#mutantP').value;
  const targets=[];for(const box of $$('.target')){const field=k=>box.querySelector(`[data-field="${k}"]`),weight=+field('weight').value;if(!weight)continue;
    if($('#inputMode').value==='qualitative'){if(field('level').value!=='unknown')targets.push({id:box.dataset.id,kind:'qualitative',level:field('level').value,weight})}
    else if(field('mean').value.trim()!=='')targets.push({id:box.dataset.id,kind:'quantitative',mean:+field('mean').value,unit:field('unit').value,uncertainty:field('uncertainty').value,error:field('error').value===''?null:+field('error').value,low:field('low').value===''?null:+field('low').value,high:field('high').value===''?null:+field('high').value,weight});
  }
  if($('#trainValues').value.trim()){const frequency=+$('#trainFrequency').value,unit=$('#trainUnits').value,sem=$('#trainSEM').value;$('#trainValues').value.split(',').forEach((s,i)=>{if(s.trim())targets.push({id:`train:${frequency}:${i+1}:${unit}`,kind:'quantitative',mean:Number(s),unit:'absolute',uncertainty:sem?'sem':'none',error:sem?+sem:null,weight:1})})}
  const keys=[],bounds={};for(const b of $$('.bound'))if(b.querySelector('[data-allow]').checked){keys.push(b.dataset.key);bounds[b.dataset.key]=[+b.querySelector('[data-min]').value,+b.querySelector('[data-max]').value]}
  const ranges={};for(const row of $$('[data-range]')){const inputs=[...row.querySelectorAll('input')],lo=Number(inputs[0].value),hi=inputs[1].value.trim()===''?null:Number(inputs[1].value);if(!(lo>=0&&Number.isFinite(lo)&&(hi===null||Number.isFinite(hi)&&hi>lo)))throw Error('Invalid qualitative range');ranges[row.dataset.range]=[lo,hi]}
  const r={referenceName:$('#reference').selectedOptions[0].textContent,reference,locks,keys,bounds,qualitativeRanges:ranges,targets,protocol:{pulses:+$('#pulses').value,pprFrequency:+$('#pprFrequency').value,recoveryFrequency:+$('#recoveryFrequency').value,frequencies:numbers($('#traceFrequencies').value),delays:numbers($('#traceDelays').value)},settings:{minimalCriterion:$('#minimalCriterion').value,mode:$('#searchMode').value,maxChanged:Math.min(keys.length,+$('#maxChanged').value),lambdaChange:+$('#lambdaChange').value,lambdaCount:+$('#lambdaCount').value,nearTolerance:+$('#nearTolerance').value/100,seed:+$('#seed').value}};E.validate(r);return r;
 }
 function cancel(){if(worker)worker.terminate();worker=null;$('#inferButton').textContent='Find candidate mechanisms'}
 $('#inferenceForm').addEventListener('input',e=>{if(e.target.matches('input,select,textarea')){const wasRunning=!!worker;cancel();if(wasRunning)$('#progress').textContent='Search stopped because inputs changed. Run inference again.';if(result){$('#results').classList.add('progress-stale');$('#progress').textContent='Inputs changed. Run inference again; displayed results belong to the previous inputs.'}}});
 $('#inferenceForm').addEventListener('submit',event=>{event.preventDefault();if(worker){cancel();$('#progress').textContent='Search cancelled. No simulator parameters changed.';return}try{const r=buildRequest();worker=new Worker('mechanism-worker.js');const active=worker;$('#inferButton').textContent='Cancel search';$('#progress').textContent='Screening individual parameters…';worker.onmessage=({data})=>{if(worker!==active)return;if(data.type==='progress')$('#progress').textContent=data.stage==='attribution'?'Calculating sufficiency, ablations and alternative mechanisms…':`Stage ${data.stage}: subset ${data.subset}/${data.total} · ${data.evaluations} simulations`;else if(data.type==='error'){cancel();$('#progress').textContent=data.message}else{cancel();result=data.result;$('#results').classList.remove('progress-stale');render(result);$('#progress').textContent=`Complete · ${result.evaluations} simulations, ${result.subsets.length} optimized subsets.`}};worker.onerror=()=>{if(worker!==active)return;cancel();$('#progress').textContent='Search could not finish. Try fewer parameters or a shorter protocol.'};worker.postMessage(r)}catch(e){cancel();$('#progress').textContent=e.message}});
 function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(t=>`<th>${esc(t)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
 function panel(title,body){return `<section class="panel"><h2>${title}</h2>${body}</section>`}
 function chart(series,{xLabel='',yLabel='',log=false,scatter=false,xMin=null,xMax=null,yMin=null,yMax=null,quadrants=false}={}){
  const W=500,H=300,l=60,r=20,t=25,b=55,points=series.flatMap(s=>s.x.map((x,i)=>[x,s.y[i]]).filter(([x,y])=>Number.isFinite(x)&&Number.isFinite(y)&&(!log||x>0)));
  if(!points.length)return '<p class="hint">No defined values for this plot.</p>';
  const loX=xMin??(log?Math.min(...points.map(p=>p[0])):Math.min(0,...points.map(p=>p[0]))),hiX=xMax??Math.max(...points.map(p=>p[0])),loY=yMin??Math.min(0,...points.map(p=>p[1])),hiY=yMax??Math.max(...points.map(p=>p[1]),.01)*1.06;
  const transform=x=>log?Math.log10(x):x,A=transform(loX),B=transform(hiX),span=Math.max(B-A,1e-9),X=x=>l+(transform(x)-A+span*.02)/(span*1.04)*(W-l-r),Y=y=>H-b-(y-loY)/Math.max(hiY-loY,1e-9)*(H-b-t);
  let svg=`<svg class="plot" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(yLabel+' by '+xLabel)}"><title>${esc(yLabel+' by '+xLabel)}</title>`;
  for(let i=0;i<=4;i++){const y=loY+(hiY-loY)*i/4;svg+=`<line x1="${l}" x2="${W-r}" y1="${Y(y)}" y2="${Y(y)}" stroke="#e1e8ec"/><text x="${l-8}" y="${Y(y)+4}" text-anchor="end" font-size="12">${fmt(y)}</text>`}
  const ticks=[];if(log){for(let decade=Math.floor(A);decade<=Math.ceil(B);decade++)for(const factor of [1,2,5]){const x=factor*10**decade;if(x>=loX&&x<=hiX)ticks.push(x)}}else for(let i=0;i<=4;i++){const value=loX+(hiX-loX)*i/4,x=xLabel==='Stimulus'||xLabel==='Maximum changed parameters'?Math.round(value):value;if(!ticks.includes(x))ticks.push(x)}
  for(const x of ticks)svg+=`<text x="${X(x)}" y="${H-b+20}" text-anchor="middle" font-size="12">${fmt(x)}</text>`;
  svg+=`<path d="M${l},${t}V${H-b}H${W-r}" fill="none" stroke="#4f6574"/>`;
  if(quadrants)svg+=`<line x1="${X(.5)}" x2="${X(.5)}" y1="${t}" y2="${H-b}" stroke="#aab6be" stroke-dasharray="3 4"/><line x1="${l}" x2="${W-r}" y1="${Y(.5)}" y2="${Y(.5)}" stroke="#aab6be" stroke-dasharray="3 4"/>`;
  for(const s of series){const pts=s.x.map((x,i)=>({x,y:s.y[i]})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&(!log||p.x>0));if(!scatter)svg+=`<path d="${pts.map((p,i)=>`${i?'L':'M'}${X(p.x)},${Y(p.y)}`).join(' ')}" fill="none" stroke="${s.color}" stroke-width="2.4" ${s.dash?'stroke-dasharray="6 4"':''}/>`;pts.forEach((p,i)=>{svg+=`<circle cx="${X(p.x)}" cy="${Y(p.y)}" r="${scatter?6:3}" fill="${s.color}" tabindex="0"><title>${esc(s.tooltip||s.name)} · ${fmt(p.x)}, ${fmt(p.y)}</title></circle>`;if(scatter)svg+=`<text x="${X(p.x)+8}" y="${Y(p.y)-7}" font-size="12">${esc(s.name)}</text>`})}
  svg+=`<text x="${(l+W-r)/2}" y="${H-10}" text-anchor="middle" font-size="13">${esc(xLabel)}</text><text transform="translate(16 ${(t+H-b)/2}) rotate(-90)" text-anchor="middle" font-size="13">${esc(yLabel)}</text></svg>`;
  return svg+(!scatter?`<div class="legend">${series.map(s=>`<span><i style="background:${s.color}"></i>${esc(s.name)}</span>`).join('')}</div>`:'');
 }
 function render(r){
  const m=r.minimal,w=r.request.reference,n=r.numerical,keys=r.request.keys,cov=percent(m.coverage),title=m.coverage===null?'WT already satisfies the selected targets':`${cov} of the selected modeled phenotype is reproduced`;
  let html=`<section class="panel key-result"><span class="badge">Most parsimonious tested candidate</span><h2>${title}</h2><p>${m.count} changed priming parameter${m.count===1?'':'s'} · ${r.subsets.length} subsets searched</p><p>${m.changed.length?m.changed.map(k=>`${E.NAMES[k]} ${m.params[k]>w[k]?'↑':'↓'}`).join(' · '):'No inferred priming change is required by these targets.'}</p><p class="hint">Coverage is relative error reduction from WT, not biological mechanism explained. Measured locks are applied separately and excluded from the changed-parameter count.</p><p>${m.rows.filter(x=>x.met).length}/${m.rows.length} observations meet their target ranges or one supplied uncertainty scale.</p><div class="toolbar"><button type="button" id="exportMechanismJSON">Export JSON</button><button type="button" id="exportMechanismCSV">Export CSV</button></div><p class="notice">${r.alternatives.length>1?'Current measurements do not uniquely distinguish these candidate mechanisms.':'Only one distinct near-optimal candidate was found; uniqueness is not established by this search.'}</p>${table(['Solution','Changed parameters','Phenotype error','Penalized objective'],[['Minimal',m.count,fmt(m.error),fmt(m.objective)],['Best numerical (tested)',n.count,fmt(n.error),fmt(n.objective)]])}<details><summary>Inspect best numerical parameters</summary>${table(['Parameter','WT','Best numerical'],keys.map(k=>[E.NAMES[k],fmt(w[k]),fmt(n.params[k])]))}</details><p class="hint">Minimal: ${r.request.settings.minimalCriterion==='coverage'?'fewest changes with at least 90% coverage (individual targets may still be missed)':'fewest changes within '+(r.request.settings.nearTolerance*100).toFixed(0)+'% of the best error'}. Changed count uses a 1% relative threshold; smaller deviations remain visible in the exported values. Errors are weighted standardized residuals, not percentages. ${esc(r.searchLimit)}</p></section>`;
  html+=panel('Phenotype reproduction',table(['Readout','WT','Observed target','Candidate','Assessment'],m.rows.map(row=>{const t=r.targets.find(t=>t.id===row.id),target=t.kind==='qualitative'?`${qualLabels[t.level]} (${fmt(t.low)}–${row.targetHigh===null?'∞':fmt(t.high)})`:`${fmt(t.low)} ± ${fmt(t.scale)} (${t.uncertainty==='none'?'default scale':t.uncertainty})`;return [esc(labels[row.id]||row.id),fmt(r.traces.wt.values[row.id]),target,fmt(row.simulated),`<span class="${row.met?'success':'notice'}">${row.met?'Within target':'Still different'}</span>`]})));
  html+=panel('Parameter identifiability',`<p class="hint">Empirical 5–95% ranges across ${r.nearOptimalCount} distinct near-optimal search samples; not statistical confidence intervals. Confidence is conditional on the chosen parameters, bounds and search depth.</p>`+table(['Parameter','WT','Candidate','Sampled range','Direction consistency','Minimal inclusion','Evidence'],r.identifiability.map(x=>[E.NAMES[x.key],fmt(w[x.key]),fmt(m.params[x.key]),`${fmt(x.low)}–${fmt(x.high)}`,percent(x.directionConsistency),percent(x.inclusion),esc(x.confidence)])));
  html+=panel('Mechanistic interpretation',r.interpretations.map(t=>`<p>${esc(t)}</p>`).join('')+'<p class="hint">These changes are consistent with the selected modeled phenotype. Necessity and sufficiency below are conditional statements within this model, not molecular causality.</p>');
  const traces=r.traces,colors={wt:'#6b7a8b',minimal:'#067d76'};
  html+=panel('Simulated response and recovery',`<div class="chart-grid">${Object.keys(traces.wt.trains).map(f=>`<div><h3>${f} Hz normalized release</h3>${chart(['wt','minimal'].map(k=>({name:k==='wt'?'WT':'Candidate',x:traces[k].trains[f].rows.map(t=>t.pulse),y:traces[k].trains[f].rows.map(t=>t.releaseNorm),color:colors[k]})),{xLabel:'Stimulus',yLabel:'Release / first',xMin:0})}</div>`).join('')}${traces.wt.recovery?`<div><h3>Recovery after ${r.request.protocol.recoveryFrequency} Hz</h3>${chart(['wt','minimal'].map(k=>({name:k==='wt'?'WT':'Candidate',x:traces[k].recovery.points.map(t=>t.interval),y:traces[k].recovery.points.map(t=>t.recovered),color:colors[k]})),{xLabel:'Probe delay (s, log)',yLabel:'Recovered fraction',log:true})}</div>`:''}</div>`);
  const pools=[['es','ES','#8797aa'],['ls','LS','#159e95'],['ts','TS','#255b90'],['tsl','TSL','#c65367'],['ers','ERS','#c89630']];
  html+=panel('Resting-state occupancy',table(['Pool','WT sites','Candidate sites','WT fraction','Candidate fraction'],pools.map(([key,label])=>[label,fmt(traces.wt.resting[key]),fmt(traces.minimal.resting[key]),percent(traces.wt.resting[key]/w.nSites),percent(traces.minimal.resting[key]/m.params.nSites)])));
  html+=panel('Necessity × sufficiency',chart(r.attribution.filter(a=>a.sufficiency!==null&&a.necessity!==null).map(a=>{const effects=Object.entries(a.phenotype).sort((x,y)=>Math.abs(y[1].ablationDelta)-Math.abs(x[1].ablationDelta));return {name:E.NAMES[a.key],x:[a.sufficiency],y:[a.necessity],color:'#087d76',tooltip:`${E.NAMES[a.key]}: WT ${fmt(w[a.key])}; mutant ${fmt(m.params[a.key])}; change ${fmt((m.params[a.key]/w[a.key]-1)*100)}%; sufficiency ${percent(a.sufficiency)}; necessity ${percent(a.necessity)}; main affected readout ${labels[effects[0]?.[0]]||effects[0]?.[0]}`}}),{scatter:true,quadrants:true,xMin:0,xMax:1,yMin:0,yMax:Math.max(1.05,...r.attribution.map(a=>a.necessity===null?0:a.necessity*1.1)),xLabel:'Sufficiency beyond measured locks',yLabel:'Necessity (normalized model difference)'})+'<p class="hint">Illustrative split at 0.5: high/high = core driver; high/low = alternative driver; low/high = required cofactor; low/low = minor contribution. Values are conditional on this candidate. Necessity can exceed 1. Measured locks remain fixed in all tests. Sufficiency measures error reduction beyond WT plus those locks, so their effect is not attributed to a kinetic parameter.</p>');
  const ids=r.targets.map(t=>t.id);html+=panel('Phenotype-specific attribution',`<p class="hint">Signed change when a parameter is reverted to WT, divided by that readout’s uncertainty scale. Blue = candidate higher; red = candidate lower. This is a model response, not a causal percentage.</p><div class="table-wrap"><table class="heat"><thead><tr><th>Reverted parameter</th>${ids.map(id=>`<th>${esc(labels[id]||id)}</th>`).join('')}</tr></thead><tbody>${r.attribution.map(a=>`<tr><th>${E.NAMES[a.key]}</th>${ids.map(id=>{const v=a.phenotype[id].ablationDelta;return `<td style="background:${v>=0?'rgba(36,118,164,':'rgba(207,87,78,'}${Math.min(.65,Math.abs(v)/5)})" title="${fmt(v)} uncertainty units">${fmt(v)}</td>`}).join('')}</tr>`).join('')}</tbody></table></div>`);
  html+=panel('Minimal-model curve',chart([{name:'Best tested model at or below this parameter count',x:r.frontier.map(v=>v.count),y:r.frontier.map(v=>v.coverage===null?NaN:100*v.coverage),color:'#087d76'}],{xLabel:'Maximum changed parameters',yLabel:'Selected modeled phenotype coverage (%)',xMin:0,yMin:0,yMax:100})+'<p class="hint">The monotonic envelope is the tested Pareto frontier. It does not imply that unsearched parameter values or subsets were excluded scientifically.</p>');
  html+=panel('Alternative mechanisms',r.alternatives.map((s,i)=>`<div class="candidate"><h3>Candidate ${String.fromCharCode(65+i)}${i===0?' · minimal':''}</h3><p>${s.changed.map(k=>`${E.NAMES[k]} ${s.params[k]>w[k]?'↑':'↓'}`).join(' · ')||'No priming changes'}</p><p>Coverage ${percent(s.coverage)} · error ${fmt(s.error)} · ${s.count} changes</p><details><summary>Parameter values</summary>${table(['Parameter','WT','Candidate'],keys.map(k=>[E.NAMES[k],fmt(w[k]),fmt(s.params[k])]))}</details><p class="hint">${s.withinNearOptimal?'Within the selected near-optimal error tolerance.':'Outside near-optimal error tolerance, but all readouts meet one uncertainty scale or their target range.'}</p></div>`).join(''));
  html+=panel('Sufficiency of parameter combinations',`<details><summary>Inspect ${r.sufficientCombinations.length} combinations from the selected candidate</summary>${table(['Changes added to WT + measured locks','Coverage','Error'],r.sufficientCombinations.map(s=>[s.keys.map(k=>E.NAMES[k]).join(' + ')||'Measured locks only',percent(s.coverage),fmt(s.error)]))}</details><details><summary>Single-parameter sensitivity screening</summary>${table(['Parameter',...ids.map(id=>labels[id]||id)],r.sensitivity.map(s=>[E.NAMES[s.key],...ids.map(id=>fmt(s.effect[id]))]))}<p class="hint">Response to +30% versus −30% perturbation, divided by WT magnitude. Bounds may limit the perturbation.</p></details>`);
  if(r.nextExperiment)html+=panel('Suggested discriminating experiment',`<p>${esc(labels[r.nextExperiment.id]||r.nextExperiment.id)}${r.nextExperiment.id.startsWith('r:')?` after ${r.nextExperiment.recoveryFrequency} Hz × ${r.nextExperiment.pulses}`:''}</p>${table(['Candidate','Predicted readout'],r.nextExperiment.predictions.map((p,i)=>[String.fromCharCode(65+i),fmt(p)]))}<p class="hint">Largest relative disagreement among the additional simulated protocols examined. This does not account for experimental noise or guarantee discrimination in real data.</p>`);
  html+=panel('Pool, calcium and fusion trajectories',`<details><summary>Inspect all frequency-dependent states</summary><label>Frequency<select id="stateFrequency">${Object.keys(traces.wt.trains).map(f=>`<option>${f}</option>`).join('')}</select></label><div id="statePlots"></div><p class="hint">Complete pre-stimulus pool counts, Ca and pFusion are included in the JSON export.</p></details>`);
  $('#results').innerHTML=html;
  function statePlots(){const f=$('#stateFrequency').value;if(!f)return;$('#statePlots').innerHTML=['ES','LS','TS','TSL','ERS','pFusion','ca'].map(key=>`<h3>${key==='ca'?'Pre-stimulus effective Ca (M)':key}</h3>${chart(['wt','minimal'].map(k=>({name:k==='wt'?'WT':'Candidate',x:traces[k].trains[f].rows.map(t=>t.pulse),y:traces[k].trains[f].rows.map(t=>t[key]),color:colors[k]})),{xLabel:'Stimulus',yLabel:key,xMin:0})}`).join('')}
  $('#stateFrequency').addEventListener('change',statePlots);statePlots();
  $('#exportMechanismJSON').addEventListener('click',()=>download('priminglab-mechanism-v46.json',JSON.stringify(r,null,2),'application/json'));
  $('#exportMechanismCSV').addEventListener('click',()=>{const rows=[['section','name','WT','candidate','target / details']];for(const k of keys)rows.push(['parameter',k,w[k],m.params[k],JSON.stringify(r.request.bounds[k])]);for(const [k,v]of Object.entries(r.request.locks))rows.push(['locked',k,w[k],v,'Measured and fixed']);for(const row of m.rows)rows.push(['phenotype',row.id,traces.wt.values[row.id],row.simulated,JSON.stringify(r.targets.find(t=>t.id===row.id))]);for(const a of r.attribution)rows.push(['attribution',a.key,a.sufficiency,a.necessity,JSON.stringify(a.phenotype)]);for(const a of r.identifiability)rows.push(['identifiability',a.key,a.low,a.high,JSON.stringify(a)]);for(const s of r.subsets)rows.push(['subset',s.keys.join('+'),s.error,s.objective,JSON.stringify(s.params)]);for(const condition of ['wt','minimal'])for(const [f,t]of Object.entries(traces[condition].trains))for(const row of t.rows)rows.push(['trace',`${condition};${f}Hz;pulse${row.pulse}`,row.release,row.releaseNorm,JSON.stringify(row)]);for(const condition of ['wt','minimal'])for(const row of traces[condition].recovery?.points||[])rows.push(['recovery',`${condition};${row.interval}s`,row.release,row.recovered,JSON.stringify(row)]);rows.push(['manifest','all settings','','',JSON.stringify({version:r.version,request:r.request,numerical:r.numerical.params,minimal:r.minimal.params,alternatives:r.alternatives.map(x=>x.params),sufficiency:r.sufficientCombinations})]);download('priminglab-mechanism-v46.csv',rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n'),'text/csv')});
 }
 $('#loadHK').addEventListener('click',async()=>{
  const button=$('#loadHK');button.disabled=true;$('#benchmarkStatus').textContent='Loading the completed blind synthetic test…';
  try{
   const response=await fetch('hk-benchmark.json');if(!response.ok)throw Error('Benchmark could not be loaded');const data=await response.json();cancel();
   const r=data.result,request=r.request;$('#reference').value='sciadv';$('#customReferenceBox').hidden=true;refreshReference();$('#inputMode').value='quantitative';mode();
   for(const box of $$('.target')){for(const field of ['mean','error','low','high'])box.querySelector(`[data-field="${field}"]`).value='';const t=request.targets.find(t=>t.id===box.dataset.id);if(t){for(const field of ['mean','unit','uncertainty','weight'])box.querySelector(`[data-field="${field}"]`).value=t[field]}}
   $('#lockN').checked=true;$('#lockP').checked=true;$('#mutantN').disabled=false;$('#mutantP').disabled=false;$('#mutantN').value=request.locks.nSites;$('#mutantP').value=request.locks.pRel0;
   $('#pulses').value=request.protocol.pulses;$('#pprFrequency').value=request.protocol.pprFrequency;$('#recoveryFrequency').value=request.protocol.recoveryFrequency;$('#traceFrequencies').value=request.protocol.frequencies.join(', ');$('#traceDelays').value=request.protocol.delays.join(', ');$('#trainValues').value='';
   $('#minimalCriterion').value=request.settings.minimalCriterion||'near';$('#searchMode').value=request.settings.mode;$('#maxChanged').value=request.settings.maxChanged;$('#lambdaChange').value=request.settings.lambdaChange;$('#lambdaCount').value=request.settings.lambdaCount;$('#nearTolerance').value=request.settings.nearTolerance*100;$('#seed').value=request.settings.seed;cost();
   result=r;$('#results').classList.remove('progress-stale');render(r);
   $('#results').insertAdjacentHTML('afterbegin',panel('HK publication comparison',`<p class="notice">Synthetic benchmark, not an independent experimental fit. The optimizer received WT, phenotype values and fixed N/pFusion only—not HK kinetic parameters.</p>${table(['Parameter','WT','Published HK · Table S2','Minimal candidate'],data.summary.comparison.map(x=>[E.NAMES[x.key],fmt(x.wt),fmt(x.publication),fmt(x.inferred)]))}<p>Locked N = 3150; pFusion = 0.379. <a href="https://www.science.org/doi/10.1126/sciadv.aea0449" target="_blank" rel="noopener">Publication</a> · <a href="hk-validation.html">Validation notes and limitations</a></p><p class="hint">This corrected Table S2 fixture is separate from the legacy forward-simulator HK preset, which has not been changed.</p>`));
   $('#progress').textContent=`Completed benchmark · ${r.evaluations} simulations. You can rerun these phenotype inputs.`;$('#benchmarkStatus').textContent='Loaded. Published rates are shown only in the comparison, not passed to inference.';
  }catch(e){$('#benchmarkStatus').textContent=e.message}finally{button.disabled=false}
 });
 function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
})();
