(()=>{
 'use strict';const C=PrimingCore,E=MechanismEngine,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let worker=null,result=null,reference;
 const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=v=>v===null||!Number.isFinite(v)?'—':Math.abs(v)>=1e5||Math.abs(v)>0&&Math.abs(v)<.001?v.toExponential(2):Number(v.toPrecision(3)).toLocaleString('en',{maximumFractionDigits:5});
 const fmtTime=v=>v===null||!Number.isFinite(v)?'Not reached':v<1?`${fmt(v*1000)} ms`:`${fmt(v)} s`;
 const fmtRatio=(value,control)=>Number.isFinite(value)&&Number.isFinite(control)&&control!==0?fmt(value/control):'—';
 const percent=x=>x===null?'Not defined':`${Math.round(x*100)}%`;
 const labels={p1:'Initial response P1',ppr:'Paired-pulse ratio',frp:'Resting FRP · LS + TS',ts:'Resting TS (vesicles)',ls:'Resting LS (vesicles)',es:'Resting ES (sites)',restTS:'Resting TS fraction','cum:200':'200 Hz cumulative release','ca:rest':'Measured resting Ca (M)','ca:ap_global':'AP global Ca proxy (M)','ca:ap_local':'AP local Ca proxy (M)','rec:auc4':'Recovery AUC · 0–4 s','rec:t50':'Time to 50% recovery (s)','rec:t80':'Time to 80% recovery (s)'};
 const allFrequencies=[5,10,20,50,100,200];for(const f of allFrequencies){labels['ss:'+f]=`${f} Hz steady-state depth · SS/P1`;labels['dep:t50:'+f]=`${f} Hz time to 50% depression (s)`;labels['dep:tss:'+f]=`${f} Hz time to steady state (s)`;labels['dep:n50:'+f]=`${f} Hz pulse at 50% depression`;labels['dep:nss:'+f]=`${f} Hz pulse at steady state`}
 for(const [time,text]of [[.02,'20 ms'],[.05,'50 ms'],[.1,'100 ms'],[.2,'200 ms'],[.25,'250 ms'],[.5,'500 ms'],[1,'1 s'],[2,'2 s'],[4,'4 s'],[8,'8 s'],[16,'16 s']])labels['r:'+time]='Recovery at '+text;
 const trainPrimary=[5,20,100,200],recoveryPrimary=['r:0.25','r:0.5','r:1','r:2','r:4','rec:auc4','rec:t50','rec:t80'];
 const extraIds=['ts','ls','es','restTS','cum:200','ca:rest','ca:ap_global','ca:ap_local',...allFrequencies.filter(f=>!trainPrimary.includes(f)).flatMap(f=>['ss:'+f,'dep:t50:'+f,'dep:tss:'+f]),'r:0.02','r:0.05','r:0.1','r:0.2','r:8','r:16'];
 const qualLabels={strongDown:'Strongly decreased',down:'Decreased',mildDown:'Mildly decreased',same:'Unchanged',mildUp:'Mildly increased',up:'Increased',strongUp:'Strongly increased'};
 function directionLabels(id){if(id.startsWith('ss:'))return{strongDown:'Strongly deeper',down:'Deeper',mildDown:'Mildly deeper',same:'Unchanged',mildUp:'Mildly shallower',up:'Shallower',strongUp:'Strongly shallower'};if(id.startsWith('dep:t')||id==='rec:t50'||id==='rec:t80')return{strongDown:'Strongly faster',down:'Faster',mildDown:'Mildly faster',same:'Unchanged',mildUp:'Mildly slower',up:'Slower',strongUp:'Strongly slower'};if(id==='rec:auc4'||id.startsWith('r:'))return{strongDown:'Strongly slower recovery',down:'Slower recovery',mildDown:'Mildly slower recovery',same:'Unchanged',mildUp:'Mildly faster recovery',up:'Faster recovery',strongUp:'Strongly faster recovery'};return qualLabels}
 function unitName(id){if(id.startsWith('dep:t')||id==='rec:t50'||id==='rec:t80')return'Seconds';if(id.startsWith('dep:n'))return'Pulse number';if(id==='rec:auc4')return'Fraction × seconds';if(id==='p1'||id.startsWith('cum:'))return'Vesicles';return'Absolute readout'}
 function targetCard(id){const directions=directionLabels(id);return `<div class="target" data-id="${id}"><h3>${labels[id]}</h3><label class="qual-only"><span class="hint">Compared with control</span><select data-field="level" aria-label="${labels[id]} direction"><option value="unknown">Unknown / not measured</option>${Object.entries(directions).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label><div class="quant-only"><div class="two"><label>Mean<input data-field="mean" type="number" step="any" aria-label="${labels[id]} mean"></label><label>Units<select data-field="unit"><option value="absolute">${unitName(id)}</option><option value="ratio" ${id==='p1'?'selected':''}>Mutant / control</option></select></label></div><details class="uncertainty"><summary>Uncertainty</summary><label>Type<select data-field="uncertainty"><option value="none">Not provided (10% scale)</option><option value="sem">SEM</option><option value="sd">SD</option><option value="scale">Reported error scale</option><option value="ci">95% confidence interval</option></select></label><label>SD / SEM<input data-field="error" type="number" min="0" step="any"></label><div class="two"><label>CI lower<input data-field="low" type="number" step="any"></label><label>CI upper<input data-field="high" type="number" step="any"></label></div><p class="hint">SD, SEM and reported error scales are used as supplied, without sample-size conversion. A 95% CI uses a normal approximation.</p></details></div><label>Within-block weight<select data-field="weight"><option value="0">Unknown / ignore</option><option value="0.5">Low</option><option value="1" selected>Normal</option><option value="3">High</option></select></label></div>`}
 const CONTROL_PRESETS=['pnas2022','pnas2024','pnas2024-olm','jp-control','sciadv'];
 $('#reference').innerHTML=CONTROL_PRESETS.map(key=>[key,C.PRESETS[key]]).map(([key,p])=>`<option value="${key}" ${key==='sciadv'?'selected':''}>${esc(p.label)}</option>`).join('')+'<option value="custom">Custom parameter set</option>';
 $('#targetInputs').innerHTML=`<section><h2>Release magnitude</h2>${targetCard('p1')}</section><section><h2>Short-term interaction</h2>${targetCard('ppr')}</section><details open><summary>Train depression · depth and kinetics</summary><p class="hint">Lower SS/P1 means deeper depression. Depression time is measured from pulse 1 in real seconds; peak release is used when facilitation precedes depression.</p>${trainPrimary.map(f=>`<section><h3>${f} Hz</h3>${['ss:'+f,'dep:t50:'+f,'dep:tss:'+f].map(targetCard).join('')}</section>`).join('')}</details><details open><summary>Recovery kinetics · primary 0–4 s window</summary><p class="hint">A larger AUC means faster recovery. Smaller t50/t80 means faster recovery. Thresholds not reached by 4 s are reported as &gt;4 s.</p>${recoveryPrimary.map(targetCard).join('')}</details>`;$('#extraInputs').innerHTML=extraIds.map(targetCard).join('');
 $('#qualRanges').innerHTML=Object.entries(E.QUAL).map(([key,[low,high]])=>`<label>${qualLabels[key]}</label><div class="two" data-range="${key}"><input aria-label="${qualLabels[key]} lower ratio" value="${low}" min="0" type="number" step="any"><input aria-label="${qualLabels[key]} upper ratio" value="${Number.isFinite(high)?high:''}" min="0" type="number" step="any"></div>`).join('');
 function readReference(){if($('#reference').value==='custom'){const parsed=JSON.parse($('#customReference').value);return {...(parsed.params||parsed.reference||parsed)}}return C.resolvePreset($('#reference').value,'publication')}
 function syncMeasured(){
  for(const [lock,input,key] of [['lockN','mutantN','nSites'],['lockP','mutantP','pRel0']]){
   const measured=$('#'+lock).checked,box=$(`.bound[data-key="${key}"] [data-allow]`);
   $('#'+input).disabled=!measured;
   if(box){box.disabled=measured;box.checked=!measured}
  }
 }
 function refreshReference(){try{reference=readReference();const rest=C.steadyState(reference);$('#wtN').textContent=`Control N_total: ${fmt(reference.nSites)} (model)`;$('#wtP').textContent=`Control: ${fmt(reference.pRel0)}`;$('#wtFRP').textContent=`Control FRP: ${fmt(rest.ls+rest.ts)} vesicles`;$('#parameterBounds').innerHTML=Object.entries(E.FAMILIES).map(([family,params])=>`<details ${['priming','calcium'].includes(family)?'open':''}><summary>${esc(({priming:'Priming kinetics',calcium:'Calcium handling',stp:'STP / facilitation',refractory:'TSL / refractory'})[family])}</summary>${params.map(key=>{const b=E.defaultBounds(reference,key);return `<div class="bound" data-key="${key}"><label><input type="checkbox" data-allow ${['priming','calcium'].includes(family)&&key!=='caRestReference'?'checked':''}> ${E.NAMES[key]}</label><div class="two"><label>Minimum<input data-min type="number" value="${b[0]}" step="any"></label><label>Maximum<input data-max type="number" value="${b[1]}" step="any"></label></div></div>`}).join('')}</details>`).join('')+['nSites','pRel0'].map(key=>{const b=E.defaultBounds(reference,key);return `<div class="bound" data-key="${key}"><label><input type="checkbox" data-allow> Infer ${E.NAMES[key]} only when unknown</label><div class="two"><label>Minimum<input data-min type="number" value="${b[0]}" step="any"></label><label>Maximum<input data-max type="number" value="${b[1]}" step="any"></label></div></div>`}).join('');syncMeasured();$('#progress').textContent='Reference ready. Describe the mutant phenotype.'}catch(e){$('#progress').textContent=e.message}}
 $('#reference').addEventListener('change',()=>{$('#customReferenceBox').hidden=$('#reference').value!=='custom';if($('#reference').value!=='custom')refreshReference()});
 $('#customReference').addEventListener('change',refreshReference);
 ['N','P'].forEach(k=>$('#lock'+k).addEventListener('change',syncMeasured));
 $$('#familyControls [data-family]').forEach(box=>box.addEventListener('change',()=>{for(const key of E.FAMILIES[box.dataset.family]){const control=$(`.bound[data-key="${key}"] [data-allow]`);if(control)control.checked=box.checked}}));
 function mode(){const m=$('#inputMode').value;$('#inferenceForm').className=m;$('#modeHint').textContent=m==='qualitative'?'Directions become broad ranges. Unknown observations carry zero weight.':'Enter means and optionally uncertainty. Blank measurements carry zero weight.'}
 $('#inputMode').addEventListener('change',mode);mode();
 function cost(){const text={fast:'Small screening search, suitable for exploration. Alternatives and identifiability will be limited.',standard:'Broader, staged searches; more computation. Larger subsets run only if simpler candidates miss the phenotype.',exhaustive:'Highest computational cost. Every subset up to the selected maximum is optimized from multiple starts; numerical search is still finite.'};$('#costHint').textContent=text[$('#searchMode').value]}
 $('#searchMode').addEventListener('change',cost);cost();refreshReference();
 const numbers=s=>s.split(/[\s,;]+/).filter(Boolean).map(Number);
 function buildRequest(){
  reference=readReference();const locks={};if($('#lockN').checked){if($('#mutantN').value.trim()==='')throw Error('Enter independently known N_total, or uncheck to mark it unknown.');locks.nSites=+$('#mutantN').value}if($('#lockP').checked){if($('#mutantP').value.trim()==='')throw Error('Enter the data-derived pFusion estimate, or uncheck to mark it unknown.');locks.pRel0=+$('#mutantP').value}
  const targets=[],addTarget=target=>{if(!targets.some(existing=>existing.id===target.id))targets.push(target)};for(const box of $$('.target')){const field=k=>box.querySelector(`[data-field="${k}"]`),weight=+field('weight').value;if(!weight)continue;
    if($('#inputMode').value==='qualitative'){if(field('level').value!=='unknown')targets.push({id:box.dataset.id,kind:'qualitative',level:field('level').value,weight})}
    else if(field('mean').value.trim()!=='')targets.push({id:box.dataset.id,kind:'quantitative',mean:+field('mean').value,unit:field('unit').value,uncertainty:field('uncertainty').value,error:field('error').value===''?null:+field('error').value,low:field('low').value===''?null:+field('low').value,high:field('high').value===''?null:+field('high').value,weight});
  }
  if($('#mutantFRP').value.trim()!==''){
   const sem=$('#frpScale').value.trim();
   targets.push({id:'frp',kind:'quantitative',mean:+$('#mutantFRP').value,unit:'absolute',uncertainty:sem?'scale':'none',error:sem?+sem:null,weight:3});
  }
  if($('#trainValues').value.trim()){
   const frequency=+$('#trainFrequency').value,unit=$('#trainUnits').value,sem=$('#trainSEM').value,raw=$('#trainValues').value.split(',').map(s=>s.trim()===''?null:Number(s));
   raw.forEach((value,i)=>{if(value!==null)addTarget({id:`train:${frequency}:${i+1}:${unit}`,kind:'quantitative',mean:value,unit:'absolute',uncertainty:sem?'sem':'none',error:sem?+sem:null,weight:1,block:'trainCurve'})});
   if(raw.every(Number.isFinite)&&raw.length>=3&&raw[0]!==0){const normalized=unit==='raw'?raw.map(value=>value/raw[0]):raw,metric=E.computeTrainPhenotype({frequency,rows:normalized.map((releaseNorm,i)=>({pulse:i+1,time:(i+1)/frequency,releaseNorm}))},frequency,+$('#steadyTolerance').value/100);for(const [id,value]of [[`ss:${frequency}`,metric.ssOverP1],[`dep:t50:${frequency}`,metric.t50Dep],[`dep:tss:${frequency}`,metric.tSS]])if(Number.isFinite(value))addTarget({id,kind:'quantitative',mean:value,unit:'absolute',uncertainty:'none',error:null,weight:1,autoCalculated:true})}
  }
  if($('#recoveryDataValues').value.trim()||$('#recoveryDataTimes').value.trim()){
   const times=numbers($('#recoveryDataTimes').value),values=numbers($('#recoveryDataValues').value),sem=$('#recoveryDataSEM').value;
   if(times.length!==values.length||times.length<2)throw Error('Recovery delays and values must contain the same number of at least two points.');
   if(!times.every((time,i)=>time>0&&time<=16&&(i===0||time>times[i-1]))||!values.every(value=>Number.isFinite(value)))throw Error('Recovery delays must increase from >0 to 16 s and values must be numeric.');
   times.forEach((time,i)=>addTarget({id:`r:${time}`,kind:'quantitative',mean:values[i],unit:'absolute',uncertainty:sem?'sem':'none',error:sem?+sem:null,weight:1,block:'recoveryCurve'}));
   const metric=E.computeRecoveryPhenotype({points:times.map((interval,i)=>({interval,recovered:values[i]}))},4);
   for(const [id,value,censored]of [['rec:auc4',metric.auc0to4,false],['rec:t50',metric.t50,metric.t50Censored],['rec:t80',metric.t80,metric.t80Censored]])if(Number.isFinite(value)&&!censored)addTarget({id,kind:'quantitative',mean:value,unit:'absolute',uncertainty:'none',error:null,weight:1,autoCalculated:true});
  }
  const keys=[],bounds={};for(const b of $$('.bound'))if(b.querySelector('[data-allow]').checked){keys.push(b.dataset.key);bounds[b.dataset.key]=[+b.querySelector('[data-min]').value,+b.querySelector('[data-max]').value]}
  const order=[...Object.values(E.FAMILIES).flat(),'nSites','pRel0'];keys.sort((a,b)=>order.indexOf(a)-order.indexOf(b));
  const ranges={};for(const row of $$('[data-range]')){const inputs=[...row.querySelectorAll('input')],lo=Number(inputs[0].value),hi=inputs[1].value.trim()===''?null:Number(inputs[1].value);if(!(lo>=0&&Number.isFinite(lo)&&(hi===null||Number.isFinite(hi)&&hi>lo)))throw Error('Invalid qualitative range');ranges[row.dataset.range]=[lo,hi]}
  const blockWeights=Object.fromEntries($$('#blockWeights [data-block]').map(input=>[input.dataset.block,+input.value]));
  const r={referenceName:$('#reference').selectedOptions[0].textContent,reference,locks,keys,bounds,qualitativeRanges:ranges,targets,blockWeights,protocol:{pulses:+$('#pulses').value,pprFrequency:+$('#pprFrequency').value,recoveryFrequency:+$('#recoveryFrequency').value,steadyTolerance:+$('#steadyTolerance').value/100,frequencies:numbers($('#traceFrequencies').value),delays:numbers($('#traceDelays').value)},settings:{minimalCriterion:$('#minimalCriterion').value,mode:$('#searchMode').value,maxChanged:Math.min(keys.length,+$('#maxChanged').value),lambdaChange:+$('#lambdaChange').value,lambdaCount:+$('#lambdaCount').value,nearTolerance:+$('#nearTolerance').value/100,seed:+$('#seed').value}};E.validate(r);return r;
 }
 function cancel(){if(worker)worker.terminate();worker=null;$('#inferButton').textContent='Find candidate mechanisms'}
 $('#inferenceForm').addEventListener('input',e=>{if(e.target.matches('input,select,textarea')){const wasRunning=!!worker;cancel();if(wasRunning)$('#progress').textContent='Search stopped because inputs changed. Run inference again.';if(result){$('#results').classList.add('progress-stale');$('#progress').textContent='Inputs changed. Run inference again; displayed results belong to the previous inputs.'}}});
 $('#inferenceForm').addEventListener('submit',event=>{event.preventDefault();if(worker){cancel();$('#progress').textContent='Search cancelled. No simulator parameters changed.';return}try{const r=buildRequest();worker=new Worker('mechanism-worker.js');const active=worker;$('#inferButton').textContent='Cancel search';$('#progress').textContent='Screening mechanism families and individual parameters…';worker.onmessage=({data})=>{if(worker!==active)return;if(data.type==='progress')$('#progress').textContent=data.stage==='attribution'?'Calculating sufficiency, ablations and alternative mechanisms…':`Stage ${data.stage}: subset ${data.subset}/${data.total} · ${data.evaluations} simulations · best error ${fmt(data.bestError)}`;else if(data.type==='error'){cancel();$('#progress').textContent=data.message}else{cancel();result=data.result;$('#results').classList.remove('progress-stale');render(result);$('#progress').textContent=`Complete · ${result.evaluations} simulations, ${result.subsets.length} optimized subsets.`}};worker.onerror=()=>{if(worker!==active)return;cancel();$('#progress').textContent='Search could not finish. Try fewer parameters or a shorter protocol.'};worker.postMessage(r)}catch(e){cancel();$('#progress').textContent=e.message}});
 function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(t=>`<th>${esc(t)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
 function panel(title,body){return `<section class="panel"><h2>${title}</h2>${body}</section>`}
 function chart(series,{xLabel='',yLabel='',log=false,scatter=false,xMin=null,xMax=null,yMin=null,yMax=null,quadrants=false}={}){
  const W=500,H=300,l=60,r=20,t=25,b=55,points=series.flatMap(s=>s.x.map((x,i)=>[x,s.y[i]]).filter(([x,y])=>Number.isFinite(x)&&Number.isFinite(y)&&(!log||x>0)));
  if(!points.length)return '<p class="hint">No defined values for this plot.</p>';
  const loX=xMin??(log?Math.min(...points.map(p=>p[0])):Math.min(0,...points.map(p=>p[0]))),hiX=xMax??Math.max(...points.map(p=>p[0])),loY=yMin??Math.min(0,...points.map(p=>p[1])),hiY=yMax??Math.max(...points.map(p=>p[1]),.01)*1.06;
  const transform=x=>log?Math.log10(x):x,A=transform(loX),B=transform(hiX),span=Math.max(B-A,1e-9),X=x=>l+(transform(x)-A+span*.02)/(span*1.04)*(W-l-r),Y=y=>H-b-(y-loY)/Math.max(hiY-loY,1e-9)*(H-b-t);
  let svg=`<svg class="plot" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(yLabel+' by '+xLabel)}"><title>${esc(yLabel+' by '+xLabel)}</title>`;
  for(let i=0;i<=4;i++){const y=loY+(hiY-loY)*i/4;svg+=`<line x1="${l}" x2="${W-r}" y1="${Y(y)}" y2="${Y(y)}" stroke="#e1e8ec"/><text x="${l-8}" y="${Y(y)+4}" text-anchor="end" font-size="12">${fmt(y)}</text>`}
  const ticks=[];if(log){for(let decade=Math.floor(A);decade<=Math.ceil(B);decade++)for(const factor of [1,2,5]){const x=factor*10**decade;if(x>=loX&&x<=hiX)ticks.push(x)}}else for(let i=0;i<=4;i++){const value=loX+(hiX-loX)*i/4,x=xLabel==='Stimulus'||xLabel==='Maximum changed parameters'?Math.round(value):value;if(!ticks.includes(x))ticks.push(x)}
  for(const x of ticks)svg+=`<text x="${X(x)}" y="${H-b+20}" text-anchor="middle" font-size="12">${fmt(x)}</text>`;
  svg+=`<path d="M${l},${t}V${H-b}H${W-r}" fill="none" stroke="#4f6574"/>`;
  if(quadrants)svg+=`<line x1="${X(.5)}" x2="${X(.5)}" y1="${t}" y2="${H-b}" stroke="#aab6be" stroke-dasharray="3 4"/><line x1="${l}" x2="${W-r}" y1="${Y(.5)}" y2="${Y(.5)}" stroke="#aab6be" stroke-dasharray="3 4"/>`;
  for(const s of series){const pts=s.x.map((x,i)=>({x,y:s.y[i]})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&(!log||p.x>0));if(!scatter)svg+=`<path d="${pts.map((p,i)=>`${i?'L':'M'}${X(p.x)},${Y(p.y)}`).join(' ')}" fill="none" stroke="${s.color}" stroke-width="2.4" ${s.dash?'stroke-dasharray="6 4"':''}/>`;pts.forEach((p,i)=>{svg+=`<circle cx="${X(p.x)}" cy="${Y(p.y)}" r="${scatter?6:3}" fill="${s.color}" tabindex="0"><title>${esc(s.tooltip||s.name)} · ${fmt(p.x)}, ${fmt(p.y)}</title></circle>`;if(scatter)svg+=`<text x="${X(p.x)+8}" y="${Y(p.y)-7}" font-size="12">${esc(s.name)}</text>`})}
  svg+=`<text x="${(l+W-r)/2}" y="${H-10}" text-anchor="middle" font-size="13">${esc(xLabel)}</text><text transform="translate(16 ${(t+H-b)/2}) rotate(-90)" text-anchor="middle" font-size="13">${esc(yLabel)}</text></svg>`;
  return svg+(!scatter?`<div class="legend">${series.map(s=>`<span><i style="background:${s.color}"></i>${esc(s.name)}</span>`).join('')}</div>`:'');
 }
 function render(r){
  const m=r.minimal,w=r.request.reference,n=r.numerical,keys=r.request.keys,cov=percent(m.coverage),title=m.coverage===null?'WT already satisfies the selected targets':`${cov} of the selected modeled phenotype is reproduced`;
  let html=`<section class="panel key-result"><span class="badge">Most parsimonious tested candidate</span><h2>${title}</h2><p>${m.count} changed parameter${m.count===1?'':'s'} · ${r.subsets.length} subsets searched</p><p>${m.changed.length?m.changed.map(k=>`${E.NAMES[k]} ${m.params[k]>w[k]?'↑':'↓'}`).join(' · '):'No inferred priming change is required by these targets.'}</p><p class="hint">Coverage is relative error reduction from WT, not biological mechanism explained. Measured locks are applied separately and excluded from the changed-parameter count.</p><p>${m.rows.filter(x=>x.met).length}/${m.rows.length} observations meet their target ranges or one supplied uncertainty scale.</p><div class="toolbar"><button type="button" id="exportMechanismJSON">Export JSON</button><button type="button" id="exportMechanismCSV">Export CSV</button></div><p class="notice">${r.alternatives.length>1?'Current measurements do not uniquely distinguish these candidate mechanisms.':'Only one distinct near-optimal candidate was found; uniqueness is not established by this search.'}</p>${table(['Solution','Changed parameters','Phenotype error','Penalized objective'],[['Minimal',m.count,fmt(m.error),fmt(m.objective)],['Best numerical (tested)',n.count,fmt(n.error),fmt(n.objective)]])}<details><summary>Inspect best numerical parameters</summary>${table(['Parameter','WT','Best numerical'],keys.map(k=>[E.NAMES[k],fmt(w[k]),fmt(n.params[k])]))}</details><p class="hint">Minimal: ${r.request.settings.minimalCriterion==='coverage'?'fewest changes with at least 90% coverage (individual targets may still be missed)':'fewest changes within '+(r.request.settings.nearTolerance*100).toFixed(0)+'% of the best error'}. Changed count uses a 1% relative threshold; smaller deviations remain visible in the exported values. Errors are weighted standardized residuals, not percentages. ${esc(r.searchLimit)}</p></section>`;
  html+=panel('Relative model support',table(['Mechanism family','Selected model error','Changed parameters','Relative support'],(r.familyModels||[]).map(f=>[esc(f.name),fmt(f.bestError),f.changed.map(k=>esc(E.NAMES[k])).join(' + ')||'—',percent(f.relativeSupport)]))+'<p class="hint">Relative support is a heuristic comparison among searched model families, conditional on the chosen targets and bounds. It is not a probability of biological causality. Combined families have more opportunities to fit; compare their complexity as well.</p>');
  html+=panel('Phenotype reproduction',table(['Readout','Control','Observed target','Candidate','Assessment'],m.rows.map(row=>{const t=r.targets.find(t=>t.id===row.id),target=t.kind==='qualitative'?`${directionLabels(row.id)[t.level]} (${fmt(t.low)}–${row.targetHigh===null?'∞':fmt(t.high)})`:`${fmt(t.low)} ± ${fmt(t.scale)} (${t.uncertainty==='none'?'default scale':t.uncertainty})`;return [esc(labels[row.id]||row.id),fmt(r.traces.wt.values[row.id]),target,fmt(row.simulated),`<span class="${row.met?'success':'notice'}">${row.met?'Within target':'Still different'}</span>`]}))+`<details><summary>Phenotype block scoring</summary>${table(['Block','Candidate error','Total block weight'],Object.entries(m.blockErrors||{}).map(([block,value])=>[esc(({release:'Release magnitude',ppr:'PPR',trainDepth:'Train depth',trainKinetics:'Train kinetics',recoveryKinetics:'Recovery kinetics',trainCurve:'Full train shape',recoveryCurve:'Full recovery shape',calcium:'Calcium measurements'})[block]||block),fmt(value.error),fmt(value.weight)]))}<p class="hint">Readouts inside one block are averaged before its total weight is applied. Adding more train or recovery samples therefore refines curve shape without multiplying that phenotype’s influence.</p></details>`);
  html+=panel('Parameter identifiability',`<p class="hint">Empirical 5–95% ranges across ${r.nearOptimalCount} distinct near-optimal search samples; not statistical confidence intervals. Confidence is conditional on the chosen parameters, bounds and search depth.</p>`+table(['Parameter','WT','Candidate','Sampled range','Direction consistency','Minimal inclusion','Evidence'],r.identifiability.map(x=>[E.NAMES[x.key],fmt(w[x.key]),fmt(m.params[x.key]),`${fmt(x.low)}–${fmt(x.high)}`,percent(x.directionConsistency),percent(x.inclusion),esc(x.confidence)])));
  html+=panel('Mechanistic interpretation',r.interpretations.map(t=>`<p>${esc(t)}</p>`).join('')+'<p class="hint">These changes are consistent with the selected modeled phenotype. Necessity and sufficiency below are conditional statements within this model, not molecular causality.</p>');
  const traces=r.traces,colors={wt:'#6b7a8b',minimal:'#067d76'};
  html+=panel('Simulated response and recovery',`<div class="chart-grid">${Object.keys(traces.wt.trains).map(f=>`<div><h3>${f} Hz normalized release</h3>${chart(['wt','minimal'].map(k=>({name:k==='wt'?'WT':'Candidate',x:traces[k].trains[f].rows.map(t=>t.pulse),y:traces[k].trains[f].rows.map(t=>t.releaseNorm),color:colors[k]})),{xLabel:'Stimulus',yLabel:'Release / first',xMin:0})}</div>`).join('')}${traces.wt.recovery?`<div><h3>Recovery after ${r.request.protocol.recoveryFrequency} Hz</h3>${chart(['wt','minimal'].map(k=>({name:k==='wt'?'WT':'Candidate',x:traces[k].recovery.points.map(t=>t.interval),y:traces[k].recovery.points.map(t=>t.recovered),color:colors[k]})),{xLabel:'Probe delay (s, log)',yLabel:'Recovered fraction',log:true})}</div>`:''}</div>`);
  const trainRows=[];for(const f of Object.keys(traces.wt.trainMetrics))for(const condition of ['wt','minimal']){const q=traces[condition].trainMetrics[f],control=traces.wt.trainMetrics[f];trainRows.push([f,condition==='wt'?'Control':'Candidate',fmt(q.ssOverP1),fmtRatio(q.ssOverP1,control.ssOverP1),fmtTime(q.t50Dep),fmtTime(q.tSS),fmtRatio(q.tSS,control.tSS),q.n50Dep??'Not reached',q.nSS??'Not reached'])}
  html+=panel('Train depression metrics',table(['Frequency (Hz)','Condition','SS/P1 · depth','Depth ratio','t50 depression','tSS','tSS ratio','N50','NSS'],trainRows)+'<p class="hint">Depth ratio &lt;1 means deeper depression; tSS ratio &lt;1 means faster onset. Times are measured from pulse 1. For non-monotonic trains, the peak response starts the depression transition. tSS requires the remaining train to stay inside the selected plateau band.</p>');
  if(traces.wt.recoveryMetrics){const control=traces.wt.recoveryMetrics,recoveryRows=['wt','minimal'].map(condition=>{const q=traces[condition].recoveryMetrics;return[condition==='wt'?'Control':'Candidate',fmt(q.r025),fmt(q.r05),fmt(q.r1),fmt(q.r2),fmt(q.r4),fmt(q.auc0to4),fmtRatio(q.auc0to4,control.auc0to4),q.t50Censored?'&gt;4 s':fmtTime(q.t50),fmtRatio(q.t50,control.t50),q.t80Censored?'&gt;4 s':fmtTime(q.t80)]});html+=panel('Recovery kinetics · 0–4 s',table(['Condition','0.25 s','0.5 s','1 s','2 s','4 s','AUC 0–4 s','AUC ratio','t50','t50 ratio','t80'],recoveryRows)+'<p class="hint">AUC ratio &gt;1 and t50 ratio &lt;1 indicate faster recovery. AUC is trapezoidal area of normalized recovery, anchored at 0 recovery at time 0. Thresholds not reached within 4 s are censored and shown as &gt;4 s; no extrapolated time is invented. Longer points remain in the plot only.</p>')}
  const pools=[['es','ES','#8797aa'],['ls','LS','#159e95'],['ts','TS','#255b90'],['tsl','TSL','#c65367'],['ers','ERS','#c89630']];
  html+=panel('Resting-state occupancy',table(['Pool','WT sites','Candidate sites','WT fraction','Candidate fraction'],[...pools.map(([key,label])=>[label,fmt(traces.wt.resting[key]),fmt(traces.minimal.resting[key]),percent(traces.wt.resting[key]/w.nSites),percent(traces.minimal.resting[key]/m.params.nSites)]),['FRP = LS + TS',fmt(traces.wt.resting.ls+traces.wt.resting.ts),fmt(traces.minimal.resting.ls+traces.minimal.resting.ts),percent((traces.wt.resting.ls+traces.wt.resting.ts)/w.nSites),percent((traces.minimal.resting.ls+traces.minimal.resting.ts)/m.params.nSites)]]));
  html+=panel('Necessity × sufficiency',chart(r.attribution.filter(a=>a.sufficiency!==null&&a.necessity!==null).map(a=>{const effects=Object.entries(a.phenotype).sort((x,y)=>Math.abs(y[1].ablationDelta)-Math.abs(x[1].ablationDelta));return {name:E.NAMES[a.key],x:[a.sufficiency],y:[a.necessity],color:'#087d76',tooltip:`${E.NAMES[a.key]}: WT ${fmt(w[a.key])}; mutant ${fmt(m.params[a.key])}; change ${fmt((m.params[a.key]/w[a.key]-1)*100)}%; sufficiency ${percent(a.sufficiency)}; necessity ${percent(a.necessity)}; main affected readout ${labels[effects[0]?.[0]]||effects[0]?.[0]}`}}),{scatter:true,quadrants:true,xMin:0,xMax:1,yMin:0,yMax:Math.max(1.05,...r.attribution.map(a=>a.necessity===null?0:a.necessity*1.1)),xLabel:'Sufficiency beyond measured locks',yLabel:'Necessity (normalized model difference)'})+'<p class="hint">Illustrative split at 0.5: high/high = core driver; high/low = alternative driver; low/high = required cofactor; low/low = minor contribution. Values are conditional on this candidate. Necessity can exceed 1. Measured locks remain fixed in all tests. Sufficiency measures error reduction beyond WT plus those locks, so their effect is not attributed to a kinetic parameter.</p>');
  const ids=r.targets.map(t=>t.id);html+=panel('Phenotype-specific attribution',`<p class="hint">Signed change when a parameter is reverted to WT, divided by that readout’s uncertainty scale. Blue = candidate higher; red = candidate lower. This is a model response, not a causal percentage.</p><div class="table-wrap"><table class="heat"><thead><tr><th>Reverted parameter</th>${ids.map(id=>`<th>${esc(labels[id]||id)}</th>`).join('')}</tr></thead><tbody>${r.attribution.map(a=>`<tr><th>${E.NAMES[a.key]}</th>${ids.map(id=>{const v=a.phenotype[id].ablationDelta;return `<td style="background:${v>=0?'rgba(36,118,164,':'rgba(207,87,78,'}${Math.min(.65,Math.abs(v)/5)})" title="${fmt(v)} uncertainty units">${fmt(v)}</td>`}).join('')}</tr>`).join('')}</tbody></table></div>`);
  html+=panel('Minimal-model curve',chart([{name:'Best tested model at or below this parameter count',x:r.frontier.map(v=>v.count),y:r.frontier.map(v=>v.coverage===null?NaN:100*v.coverage),color:'#087d76'}],{xLabel:'Maximum changed parameters',yLabel:'Selected modeled phenotype coverage (%)',xMin:0,yMin:0,yMax:100})+'<p class="hint">The monotonic envelope is the tested Pareto frontier. It does not imply that unsearched parameter values or subsets were excluded scientifically.</p>');
  html+=panel('Alternative mechanisms',r.alternatives.map((s,i)=>`<div class="candidate"><h3>Candidate ${String.fromCharCode(65+i)}${i===0?' · minimal':''}</h3><p>${s.changed.map(k=>`${E.NAMES[k]} ${s.params[k]>w[k]?'↑':'↓'}`).join(' · ')||'No priming changes'}</p><p>Coverage ${percent(s.coverage)} · error ${fmt(s.error)} · ${s.count} changes</p><details><summary>Parameter values</summary>${table(['Parameter','WT','Candidate'],keys.map(k=>[E.NAMES[k],fmt(w[k]),fmt(s.params[k])]))}</details><p class="hint">${s.withinNearOptimal?'Within the selected near-optimal error tolerance.':'Outside near-optimal error tolerance, but all readouts meet one uncertainty scale or their target range.'}</p></div>`).join(''));
  html+=panel('Sufficiency of parameter combinations',`<details><summary>Inspect ${r.sufficientCombinations.length} combinations from the selected candidate</summary>${table(['Changes added to WT + measured locks','Coverage','Error'],r.sufficientCombinations.map(s=>[s.keys.map(k=>E.NAMES[k]).join(' + ')||'Measured locks only',percent(s.coverage),fmt(s.error)]))}</details><details><summary>Single-parameter sensitivity screening</summary>${table(['Parameter',...ids.map(id=>labels[id]||id)],r.sensitivity.map(s=>[E.NAMES[s.key],...ids.map(id=>fmt(s.effect[id]))]))}<p class="hint">Response to +30% versus −30% perturbation, divided by WT magnitude. Bounds may limit the perturbation.</p></details>`);
  if(r.nextExperiment)html+=panel('Suggested discriminating experiment',`<p>${esc(labels[r.nextExperiment.id]||r.nextExperiment.id)}${r.nextExperiment.id.startsWith('r:')?` after ${r.nextExperiment.recoveryFrequency} Hz × ${r.nextExperiment.pulses}`:''}</p>${table(['Candidate','Predicted readout'],r.nextExperiment.predictions.map((p,i)=>[String.fromCharCode(65+i),fmt(p)]))}<p class="hint">Largest relative disagreement among the additional simulated protocols examined. This does not account for experimental noise or guarantee discrimination in real data.</p>`);
  html+=panel('Pool, calcium and fusion trajectories',`<details><summary>Inspect all frequency-dependent states</summary><label>Frequency<select id="stateFrequency">${Object.keys(traces.wt.trains).map(f=>`<option>${f}</option>`).join('')}</select></label><div id="statePlots"></div><p class="hint">Complete pre-stimulus pool counts, Ca and pFusion are included in the JSON export.</p></details>`);
  $('#results').innerHTML=html;
  function statePlots(){const f=$('#stateFrequency').value;if(!f)return;$('#statePlots').innerHTML=['ES','LS','TS','TSL','ERS','pFusion','ca'].map(key=>`<h3>${key==='ca'?'Pre-stimulus effective Ca (M)':key}</h3>${chart(['wt','minimal'].map(k=>({name:k==='wt'?'WT':'Candidate',x:traces[k].trains[f].rows.map(t=>t.pulse),y:traces[k].trains[f].rows.map(t=>t[key]),color:colors[k]})),{xLabel:'Stimulus',yLabel:key,xMin:0})}`).join('')}
  $('#stateFrequency').addEventListener('change',statePlots);statePlots();
  $('#exportMechanismJSON').addEventListener('click',()=>download('priminglab-mechanism-v49.json',JSON.stringify(r,null,2),'application/json'));
  $('#exportMechanismCSV').addEventListener('click',()=>{const rows=[['section','name','WT','candidate','target / details']];for(const k of keys)rows.push(['parameter',k,w[k],m.params[k],JSON.stringify(r.request.bounds[k])]);for(const [k,v]of Object.entries(r.request.locks))rows.push(['locked',k,w[k],v,'Data-derived and fixed']);for(const row of m.rows)rows.push(['phenotype',row.id,traces.wt.values[row.id],row.simulated,JSON.stringify(r.targets.find(t=>t.id===row.id))]);for(const condition of ['wt','minimal'])for(const [f,q]of Object.entries(traces[condition].trainMetrics))rows.push(['train-metrics',`${condition};${f}Hz`,q.ssOverP1,q.t50Dep,JSON.stringify(q)]);for(const condition of ['wt','minimal'])if(traces[condition].recoveryMetrics)rows.push(['recovery-metrics',condition,traces[condition].recoveryMetrics.auc0to4,traces[condition].recoveryMetrics.t50,JSON.stringify(traces[condition].recoveryMetrics)]);for(const a of r.attribution)rows.push(['attribution',a.key,a.sufficiency,a.necessity,JSON.stringify(a.phenotype)]);for(const a of r.identifiability)rows.push(['identifiability',a.key,a.low,a.high,JSON.stringify(a)]);for(const s of r.subsets)rows.push(['subset',s.keys.join('+'),s.error,s.objective,JSON.stringify(s.params)]);for(const condition of ['wt','minimal'])for(const [f,t]of Object.entries(traces[condition].trains))for(const row of t.rows)rows.push(['trace',`${condition};${f}Hz;pulse${row.pulse}`,row.release,row.releaseNorm,JSON.stringify(row)]);for(const condition of ['wt','minimal'])for(const row of traces[condition].recovery?.points||[])rows.push(['recovery',`${condition};${row.interval}s`,row.release,row.recovered,JSON.stringify(row)]);rows.push(['manifest','all settings','','',JSON.stringify({version:r.version,request:r.request,numerical:r.numerical.params,minimal:r.minimal.params,alternatives:r.alternatives.map(x=>x.params),sufficiency:r.sufficientCombinations})]);download('priminglab-mechanism-v49.csv',rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n'),'text/csv')});
 }
 function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
})();
