'use strict';
// In-memory DOM checks; no browser access or network requests.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const dist=path.join(__dirname,'../dist'),dom=new JSDOM(fs.readFileSync(path.join(dist,'mechanism.html'),'utf8'),{runScripts:'outside-only',url:'https://example.invalid/mechanism.html'}),w=dom.window;
w.structuredClone=structuredClone;
let lastRequest,requests=0,terminated=0;
w.Worker=class{terminate(){this.cancelled=true;terminated++}postMessage(r){lastRequest=JSON.parse(JSON.stringify(r));requests++;setTimeout(()=>{if(this.cancelled)return;try{const result=w.MechanismEngine.infer({...r,settings:{...r.settings,iterations:2}});this.onmessage({data:{type:'result',result}})}catch(e){this.onmessage({data:{type:'error',message:e.message}})}},0)}};
for(const file of ['sim-core.js','mechanism-engine.js','mechanism-ui.js'])w.eval(fs.readFileSync(path.join(dist,file),'utf8'));
const $=s=>w.document.querySelector(s),input=(s,v)=>{$(s).value=String(v);$(s).dispatchEvent(new w.Event('input',{bubbles:true}))},change=(s,v)=>{input(s,v);$(s).dispatchEvent(new w.Event('change',{bubbles:true}))};
const run=()=>$('#inferenceForm').dispatchEvent(new w.Event('submit',{cancelable:true,bubbles:true})),wait=()=>new Promise(resolve=>setTimeout(resolve,1200));
(async()=>{
 assert.equal($('#reference').value,'sciadv');assert.equal($('#lockP').checked,true);assert.equal($('#lockN').checked,true);assert.equal($('#mutantP').disabled,false);
 assert.ok($('.bound[data-key="caRestActual"]'));assert.ok($('.bound[data-key="caRestReference"]'));assert.notEqual($('.bound[data-key="caRestActual"]'),$('.bound[data-key="caRestReference"]'));
 run();assert.match($('#progress').textContent,/Enter independently known N_total/);assert.equal(requests,0);
 $('#lockN').checked=false;$('#lockN').dispatchEvent(new w.Event('change'));input('#mutantP',.379);input('#mutantFRP',2100);input('#frpScale',100);
 $('#familyControls [data-family="calcium"]').click();for(const key of ['kf1','kb1','slope1','kb2','slope2'])$('.bound[data-key="'+key+'"] [data-allow]').checked=false;
 input('#pulses',8);input('#traceFrequencies','200');input('#traceDelays','.1');input('#maxChanged',1);change('#searchMode','fast');input('[data-id="p1"] [data-field="level"]','strongUp');
 run();await wait();assert.match($('#progress').textContent,/Complete/);assert.equal(lastRequest.locks.pRel0,.379);assert.equal(lastRequest.locks.nSites,undefined);
 assert.equal(lastRequest.targets.find(t=>t.id==='frp').mean,2100);assert.deepEqual(lastRequest.keys,['kf2','nSites']);
 assert.match($('#results').textContent,/Relative model support/);assert.match($('#results').textContent,/Necessity × sufficiency/);
 assert.ok(!$('#results').innerHTML.includes('NaN'));
 change('#inputMode','quantitative');assert.ok($('#results').classList.contains('progress-stale'));
 input('[data-id="p1"] [data-field="mean"]',1.5);input('[data-id="p1"] [data-field="uncertainty"]','sem');input('[data-id="p1"] [data-field="error"]',.1);run();await wait();
 assert.match($('#progress').textContent,/Complete/);assert.equal(lastRequest.targets[0].error,.1);
 $('#lockN').checked=true;$('#lockN').dispatchEvent(new w.Event('change'));input('#mutantN',3500);run();await wait();assert.equal(lastRequest.locks.nSites,3500);assert.ok(!lastRequest.keys.includes('nSites'));
 input('#mutantP',2);run();assert.match($('#progress').textContent,/Invalid locked/);
 assert.equal($('#benchmarkButtons'),null);assert.equal($('#revealPublication'),null);assert.equal($('#publicationComparison'),null);
 assert.ok(!fs.readFileSync(path.join(dist,'mechanism.html'),'utf8').includes('mechanism-benchmarks'));
 console.log('Mechanism DOM checks passed: hard locks, distinct calcium controls, generic family selection, and publication-agnostic production UI. '+requests+' worker requests; '+terminated+' terminations.');w.close();
})().catch(e=>{console.error(e);process.exitCode=1;w.close()});
